# Change baseurl before deploy
baseurl = "https://csc-ubc-okanagan.github.io/csc-data-blog/"
languageCode = "en-us"
title = "R & Python Blog"
copyright = "Center for Scholarly Communication, UBC Okanagan"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = ""

[pagination]
pagerSize = 6
	
[params.article]
math = true

[services]
  [services.googleAnalytics]
    googleAnalytics = 'G-PQ1KG9NWP0'
	
